### ISSUE TITLE
Download the Raw Data

### ISSUE THREAD

**Issue by wengxyu1030** [wengxyu1030/MIS#1]
Please download the MIS data based on the MIS assigned in TOR https://docs.google.com/spreadsheets/d/18woWQtzVmdPEKfqFsrVbj3NZ0otUdikw_0PTGexUHUM/edit#gid=0 

- The data could be downloaded from https://dhsprogram.com/data/available-datasets.cfm
- Please use the username and password provided by the World Bank team to download the raw data. 
- The raw data should be saved in the folder: https://1drv.ms/u/s!Asjjf4e9y-vXtB0oC9mFFdAetCwO?e=LUHp50
- Please use the renaming rules when saving the raw data from DHS website to the MIS folder.

**Comment by robin-wang** [comment]
This step is no longer performed a priori. JW is downloading data as new cases are assigned. 
20210622 RW
