### ISSUE TITLE
Update user identified directory

### ISSUE THREAD

**Issue by wengxyu1030** [wengxyu1030/MIS#10]
Hi @imarabbit , could you let me know your state user name? Using the code below would work. 
`dis "`c(username)'"`

**Comment by jianingwwww** [comment]
Hi @wengxyu1030 , did you mean stata user name? I typed in the dis "`c(username)'" and it returned wu_jn. I guess that might be my stata username? Thank you for checking~

**Comment by wengxyu1030** [comment]
Thanks, this is helpful.
